### ISSUE TITLE
[Task] Create theme files for Omen theme

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-themes#16]
**Task Description:**
Themes is a **major feature of React ChatBotify v2**. This repository is necessary as part of the [**solutioning for themes**](https://tjtanjin.medium.com/behind-the-scenes-solutioning-for-react-chatbotifys-themes-a59576043d4a).

As part of ongoing work, it would be great to create more themes as a community. Specifically for this task, we're looking at **creating the theme files** necessary to bring the `Omen` theme to life. An image of the theme is as follow:

<img width="310" alt="Screenshot 2024-10-07 at 12 32 25 AM" src="https://github.com/user-attachments/assets/7acaf786-22b1-46db-b25f-4ea733711c59">

**Deliverable(s):**
Theme files (e.g. `meta.json`, `display.png`, `settings.json`, `styles.json`, `styles.css`) that successfully create the `Omen` theme (best-effort).

Note that while it is ideal for the implementation to be 100% identical to the design, this is **not always possible**. A **best effort implementation** with slight deviations may be acceptable as long as it doesn't stray too far off.

**Additional Context:**
- Guide for creating themes can be found [**here**](https://github.com/tjtanjin/react-chatbotify-themes?tab=readme-ov-file#creating-themes)
- Merged PRs for themes can be referenced [**here**](https://github.com/tjtanjin/react-chatbotify-themes/pulls?q=is%3Apr+is%3Aclosed)
- Usage of themes in the chatbot can be found in examples [**here**](https://react-chatbotify.com/docs/examples/single_theme) and [**here**](https://react-chatbotify.com/docs/examples/multiple_themes)

**Comment by CodeStrate** [comment]
Would like to be assigned to this issue. Thanks 👍

**Comment by tjtanjin** [comment]
> Would like to be assigned to this issue. Thanks 👍

Go for it!

**Comment by CodeStrate** [comment]
@tjtanjin While working on the theme, this is something that happens in my projects too, the border has this weird pixelation issue.
![image](https://github.com/user-attachments/assets/c776de1c-e1a7-4881-8898-b3d0a4a5606f)

Do you have any guidance for me?

**Comment by tjtanjin** [comment]
> @tjtanjin While working on the theme, this is something that happens in my projects too, the border has this weird pixelation issue. ![image](https://private-user-images.githubusercontent.com/56911705/375744159-c776de1c-e1a7-4881-8898-b3d0a4a5606f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTkzNDMsIm5iZiI6MTcyODcxOTA0MywicGF0aCI6Ii81NjkxMTcwNS8zNzU3NDQxNTktYzc3NmRlMWMtZTFhNy00ODgxLTg4OTgtYjNkMGE0YTU2MDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEyVDA3NDQwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0N2ViNzQ3OTZkYzdiY2Y5Y2U1NmMzZWE2NWE4ZDkwYWZhYzc0MGFjNTMxZDNmMDQyZjM4NWI5ZWQ2YTdjYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WGYuxlAtyaEgCgXUx86EvDdfQkb01lx36Pe3aZ6-KvA)
> 
> Do you have any guidance for me?

Hmmm, might be a render issue. Took a closer look and saw this too:
<img width="321" alt="Screenshot 2024-10-12 at 3 49 31 PM" src="https://github.com/user-attachments/assets/5cf1ecdf-3d38-4714-80d8-4107afac2d3d">

Not sure if there's a clean workaround for this (that doesn't involve hacking too much). It's not a huge thing given how subtle it is, but if you have the time and are keen to explore feel free to dive into it (and perhaps make a PR to fix the main repository as well 😝).

**Comment by CodeStrate** [comment]
![image](https://github.com/user-attachments/assets/cba1b536-b916-40bd-8a34-7f30b73a53a8)

using styles to change the section colors result in these white margins and imported icons don't take styles.

**Comment by CodeStrate** [comment]
#45 created the theme. Check it out @tjtanjin any changes?
