### ISSUE TITLE
[Task] Create mockups for Sunset Orange theme 

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-themes#20]
**Task Description:**  
Themes is a **major feature of React ChatBotify v2**. This repository is necessary as part of the [**solutioning for themes**](https://tjtanjin.medium.com/behind-the-scenes-solutioning-for-react-chatbotifys-themes-a59576043d4a).

As part of ongoing work, it would be great to create more themes as a community. Specifically for this task, we're looking at **creating the mockups** necessary to bring a theme called `Sunset Orange` to life.

The description that we are going for this theme is: **Vibrant orange gradients mixed with soft purples and pinks, mimicking the colors of a sunset sky.**

**Deliverable(s):**  
Mockups for the `Sunset Orange` theme. This can be in the form of figma designs or images (visuals of the theme will suffice for reference in creating the theme files).

Note that for the creation of mockups, creativity is largely, if not completely left up to the designer. The only request is to stay reasonably relevant to the proposed theme (or if you have ideas for a totally different theme, feel free to create a separate issue).

**Additional Context:**  
- Upon completion of the mockup, create a separate issue to track the creation of its theme files (an example can be seen [**here**](https://github.com/tjtanjin/react-chatbotify-themes/issues/16)).

**Comment by haingo-raz** [comment]
Hi @tjtanjin! I'm interested in working on this.

**Comment by tjtanjin** [comment]
> Hi @tjtanjin! I'm interested in working on this.

Go for it!

**Comment by haingo-raz** [comment]
Here is a mockup I came up with:

![image](https://github.com/user-attachments/assets/1534ce0a-b185-4767-ba93-752e196a3f30)

**Comment by tjtanjin** [comment]
> Here is a mockup I came up with:
> 
> ![image](https://private-user-images.githubusercontent.com/100688816/376053749-1534ce0a-b185-4767-ba93-752e196a3f30.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwOTAyNDYsIm5iZiI6MTcyOTA4OTk0NiwicGF0aCI6Ii8xMDA2ODg4MTYvMzc2MDUzNzQ5LTE1MzRjZTBhLWIxODUtNDc2Ny1iYTkzLTc1MmUxOTZhM2YzMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNlQxNDQ1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNThhNzdhNTdiMTAyMzhjNDk0N2E4ODk1MzI2NDE4OWNmN2U4ZDE1Njk5YjhhOWNmY2Q3ZTgzMDM1NWM2Nzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DYvGu9m-3anQR1n3DWVB0yJe4Uz3tGtQIhikCsxGDrk)

Thank you @haingo-raz, would you be keen to work on the files (e.g. `styles.css`) for the theme as well?

**Comment by haingo-raz** [comment]
Yes!

**Comment by tjtanjin** [comment]
> Yes!

Great! I've created an issue [**here**](https://github.com/tjtanjin/react-chatbotify-themes/issues/40) 😊

**Comment by haingo-raz** [comment]
Thanks! Working on it.
