### ISSUE TITLE
[Task] Create mockups for Frosted Glass theme

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-themes#21]
**Task Description:**  
Themes is a **major feature of React ChatBotify v2**. This repository is necessary as part of the [**solutioning for themes**](https://tjtanjin.medium.com/behind-the-scenes-solutioning-for-react-chatbotifys-themes-a59576043d4a).

As part of ongoing work, it would be great to create more themes as a community. Specifically for this task, we're looking at **creating the mockups** necessary to bring a theme called `Frosted Glass` to life.

The description that we are going for this theme is: **A sleek, modern theme using translucent elements, soft blues, and whites to create a frosted glass effect.**

**Deliverable(s):**  
Mockups for the `Frosted Glass` theme. This can be in the form of figma designs or images (visuals of the theme will suffice for reference in creating the theme files).

Note that for the creation of mockups, creativity is largely, if not completely left up to the designer. The only request is to stay reasonably relevant to the proposed theme (or if you have ideas for a totally different theme, feel free to create a separate issue).

**Additional Context:**  
- Upon completion of the mockup, create a separate issue to track the creation of its theme files (an example can be seen [**here**](https://github.com/tjtanjin/react-chatbotify-themes/issues/16)).

**Comment by VAmanjain** [comment]
Thank you for the detailed task description!

I'm excited to contribute to the Frosted Glass theme for React ChatBotify v2. I'll begin by designing mockups based on the description provided, focusing on a sleek, modern theme with translucent elements and a frosted glass effect, using soft blues and whites. The designs will emphasize the frosty, elegant atmosphere you're aiming for.

The mockups will be delivered as images or Figma files to ensure they can be referenced while creating the theme files. Once the mockups are ready, I'll open a separate issue to track the development of the actual theme files.

I am looking forward to bringing this idea to life!

Kindly assign me this task.

**Comment by tjtanjin** [comment]
> Thank you for the detailed task description!
> 
> I'm excited to contribute to the Frosted Glass theme for React ChatBotify v2. I'll begin by designing mockups based on the description provided, focusing on a sleek, modern theme with translucent elements and a frosted glass effect, using soft blues and whites. The designs will emphasize the frosty, elegant atmosphere you're aiming for.
> 
> The mockups will be delivered as images or Figma files to ensure they can be referenced while creating the theme files. Once the mockups are ready, I'll open a separate issue to track the development of the actual theme files.
> 
> I am looking forward to bringing this idea to life!
> 
> Kindly assign me this task.

Hey @VAmanjain, appreciate the enthusiasm! Assigned the issue! 😊

**Comment by VAmanjain** [comment]
Hey @tjtanjin, Can you explain to me how can I test my mockup in your chatbot?
I took a reference of this page but I can't get my response. Did you have any resources to test the local mockup into your Chatbot component?
![image](https://github.com/user-attachments/assets/424156c8-101f-4ee8-b682-ce269c2fad9b)

**Comment by tjtanjin** [comment]
Hey @VAmanjain! There are no tests for mockups which are solely focused on design. If you're referring to implementing the actual styling, that's to be created as a separate issue with the details found in the README of this repository.

**Comment by VAmanjain** [comment]
Okk @tjtanjin
