### ISSUE TITLE
[Task] Add pull request template for themes

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-themes#6]
There are currently no templates for opening pull requests for themes. It would be great to have a template of checklist to remind users what to look out for:

I have noted the following commonly overlooked [styles](https://react-chatbotify.tjtanjin.com/docs/api/bot_options#styles):
- [x] botOptionStyle
- [x] botCheckboxRowStyle
- [x] botCheckMarkStyle
- [x] chatHistoryButtonStyle
- [x] chatButtonStyle

**Comment by Deepak0320Singhal** [comment]
Hey, I would love to work on this issue.

**Comment by Bashamega** [comment]
I would like to work on this

**Comment by tjtanjin** [comment]
> I would like to work on this

Sure thing! 😊
