### ISSUE TITLE
[Task] Add issue templates

### ISSUE THREAD

**Issue by tjtanjin** [tjtanjin/react-chatbotify-themes#7]
There are currently no templates for opening issues It would be great to have a template to guide users who wish to raise issues. Can consider taking reference from the [React ChatBotify repository](https://github.com/tjtanjin/react-chatbotify).

**Comment by Deepak0320Singhal** [comment]
I would like to work on this issue, can you assign this issue to me.

**Comment by Bashamega** [comment]
Hello:) if @Deepak0320Singhal doesn't want to work on this issue i can work on this issue

**Comment by tjtanjin** [comment]
> Hello:) if @Deepak0320Singhal doesn't want to work on this issue i can work on this issue

There's actually an initial template that @Deepak0320Singhal has already created which you can find in the codebase. That said, if you wish to, you can improve upon the template to better contextualise it (e.g. the reference inside to improve the library isn't very accurate because this isn't the library repository).
